services:
  homeassistant:
    container_name: homeassistant
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/gpiomem:/dev/gpiomem             # Share Raspberry Pi GPIOs devices
    volumes:
      - ./config:/config                      # Home Assistant config directory only
      - /etc/localtime:/etc/localtime:ro      # Linux hosts only, you can also use environment: - TZ=Country/City
    restart: unless-stopped
    privileged: true
    network_mode: host
