
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ME
# Shell commands aren’t allowed for a camel-case naming, please use lowercase naming only and separate the names with underscores.
shell_command:
  restart_lircd: rc-service lircd restart           # Don't remove!
  lg_stereo_remote_key_power: irsend send_once lg_stereo_remote key_power       # Custom, can be removed
  lg_stereo_remote_key_volume_up: irsend send_once lg_stereo_remote key_volume_up       # Custom, can be removed
  lg_stereo_remote_key_volume_down: irsend send_once lg_stereo_remote key_volume_down       # Custom, can be removed
